# Welcome to Jekyll!
#

# Site settings
title: JoJo Te Guia
description: |
  Guiando há mais de 5 anos passeios dinâmicos e  
  realizando roteiros turísticos  
  únicos pela cidade de Orlando.  
owner: JoJo # or company name
first_published: 2019 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: {{email}}
  #flickr:
  instagram: https://www.instagram.com/jojoteguia/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

testimonies:
    - name: Gabriel e Bruna
      home-country: Porto Alegre - Brasil
      testimony: Jonas é incrível e seu trabalho é muito bom. Conhece cada macete dos parques para que aproveitemos tudo o que dá a cada dia. Obrigado pelos momentos mágicos! 
      picture: images/gabriel_bruna.jpg
    - name: Manuela
      home-country: Salvador - Brasil
      testimony: Trabalho do Jonas é impecável, tem muita paciência com adultos e crianças. Adoramos foi incrível eu super recomendo. Trabalho incrível!
      picture: images/manoela.jpeg
    - name: Beatriz Correa
      home-country: Rio de Janeiro - Brasil
      testimony: Jonas é muito animado e fez nosso passeio ser incrível. Parabéns pelo profissional que você é!
      picture: images/beatriz_correa.jpeg
    - name: Fernanda Damenan
      home-country: Rio de Janeiro - Brasil
      testimony: Jonas é uma pessoa incrível, sempre com um baita astral! Já estamos com saudades!
      picture: images/fernanda_damenan.jpeg


# Build settings
markdown: kramdown
#sass:
#  style: compressed
 